### ISSUE TITLE
Earthly 0.5.15 fails to run commands

### ISSUE THREAD

**Issue by omerbenamram** [earthly/earthly#1026]
Hi,

After updating earthly from  0.5.13 to  0.5.15, every command fails with some variation of this message:
```
Error getting earthly dir: lookup user for homedir: user: unknown userid 116002263
```

Reverting to  0.5.13 fixes it.

Wondering if this is related to https://github.com/earthly/earthly/pull/977?

**Comment by alexcb** [comment]
Thanks for the report @omerbenamram , can you let us know what OS you are using?

**Comment by omerbenamram** [comment]
@alexcb Ubuntu 18.04 :)

**Comment by alexcb** [comment]
@omerbenamram I haven't been able to replicate the issue, but I've tried changing some error handling in the home directory detection code.

Since I can't replicate the issue, would you be able to try out this new code to see if this fixes the issue for you?

You should be able to compile earthly out of my branch via:

    mkdir /tmp/test-earthly-fix && cd /tmp/test-earthly-fix && git clone https://github.com/earthly/earthly.git . && git checkout ignore-errors-when-detecting-home-dir && earthly +for-linux && ls ./build/linux/amd64/earthly

Then if you run `./build/linux/amd64/earthly --version`, you should see the git branch and sha referenced:

    earthly version ignore-errors-when-detecting-home-dir-95fe6666001aeb4031be7c174681cefd012354ca linux/amd64

Thanks.

**Comment by omerbenamram** [comment]
This version indeed runs as expects :)

**Comment by alexcb** [comment]
Thanks for giving it a test :)

I'll work on getting this branch ready to merge into main, it might be tomorrow by the time we get a fix released.

**Comment by alexcb** [comment]
This has been released under https://github.com/earthly/earthly/releases/tag/v0.5.16
