### ISSUE TITLE
Add built-in vars to expose the host os/platform

### ISSUE THREAD

**Issue by mariusvniekerk** [earthly/earthly#1228]
Presently it is not easily possible to know what the host os/platform is.  This is particularly importatnt when working on a machine like an m1 macbook that tends to run lots of portions under emulation.

For example you may want to do something like the following (mostly to avoid golang crashing instant under qemu)

```
go-cross-amd64:
    FROM --platform=linux/${HOST_PLATFORM} golang:1.17.1
    # Setup cross compiler toolchain if not running on host platform
    IF [ ${HOST_PLATFORM} != "amd64" ]
        RUN dpkg --add-architecture amd64
        RUN apt-get update
        RUN apt-get install -y gccgo-x86-64-linux-gnu
        ENV CC=x86_64-linux-gnu-gcc
        ENV PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig
    END
    
	COPY . /work
	WORKDIR /work
    RUN GOOS=linux GOARCH=amd64 CGO=1 go build \
        -o ./processor cmd/main.go
```

**Comment by vladaionescu** [comment]
BTW, we should probably use `USERPLATFORM` (e.g. `linux/arm/v7`), `USEROS` (e.g. `linux`), `USERARCH` (e.g. `arm`) and `USERVARIANT` (e.g. `v7`) so that this matches the already existing `TARGETPLATFORM`, `TARGETOS`, `TARGETARCH` and `TARGETVARIANT`.

I'm also thinking `USER*` instead of `HOST*` as future Earthly builds will not be constrained to one machine. I'm thinking `USER*` is more suggestive that this is the platform of the user who initiated the build.

**Comment by am-a-man** [comment]
Hey,
I'd like to work on this, please assign this to me.
Also I'm fairly new to Open Source, it would be great if you could provide with some help.

**Comment by RiyaGupta89** [comment]
May I work on this issue? @vladaionescu

**Comment by pragun-ananda** [comment]
Hi, I'm interested in working on this issue (or issues of similar difficulty) as well. This is my first Hacktoberfest so I'd love some guidance! @mariusvniekerk

**Comment by vladaionescu** [comment]
This is taken by @akranz01
