### ISSUE TITLE
Trouble getting caching to work in Github Actions.

### ISSUE THREAD

**Issue by ianpurton** [earthly/earthly#1620]
My github action is at https://github.com/purton-tech/barricade/blob/master/.github/workflows/ci.yml

I run earthly like this

```
- name: Run build and Deploy Containers
    if: github.ref == 'refs/heads/master'
      run: earthly --allow-privileged --ci --remote-cache=purtontech/barricade:cache --push +integration-test
```

My Earthfile is here https://github.com/purton-tech/barricade/blob/master/Earthfile

An example run is here https://github.com/purton-tech/barricade/actions/runs/1768425906

The cache is not found as Earthly starts however is does seem to push something to the cache at the end of the build.

I get lots of log entries that look like it pushes the cache.

```

               cache | [██████████] preparing build cache for export ... 100%
               cache | [          ] writing layer sha256:00a2a30878c1adf2cc7e737acaa9778c5839201d292b08ca006f13cccd0a008b ... 0%
```

However the cache image in docker hub is empty. https://hub.docker.com/r/purtontech/barricade/tags

Is there something else I should be doing?

Thanks

**Comment by vladaionescu** [comment]
Hi @ianpurton - I don't see anything obvious in the setup. The fact that the cache image in docker hub looks empty is actually expected - the image is in a format that the UI doesn't quite recognize (it's not a regular image). The output does seem to say that a cache export is going on, so that's good.

The fact that the cache is not found is possibly the main cause here.

```
               cache | WARN: (importing cache manifest from ***/barricade:cache) docker.io/***/barricade:cache: not found
               cache | WARN: (importing cache manifest from ***/barricade:latest) docker.io/***/barricade:latest: not found
```

It seems that GHA is obfuscating part of the image name, from what I'm seeing in the logs. Perhaps it's worth double checking that the name is correct (GHA obfuscates strings it finds in any secret).

* Does this reproduce when running the build locally? (it might be easier to iterate on the build on your computer while we find the root cause)
* Could you provide logs for this running in `--verbose`? (Just in case there's more detail there)
* Something else to try: if it still doesn't work, it could be worth checking if the latest version of Earthly works instead. In case it's a bug, it could be something we've already fixed

**Comment by ianpurton** [comment]
Getting the latest version seemed to fix it. Thanks.
