### ISSUE TITLE
Incorrect `Please update your buildkit installation` warning

### ISSUE THREAD

**Issue by vladaionescu** [earthly/earthly#2288]
Example Earthfile

```Earthfile
VERSION 0.6

postgres:
    FROM postgres:11.8
    SAVE IMAGE earthly/compute-postgres:main

up:
    LOCALLY
    WITH DOCKER --load=+postgres
        RUN echo "There might be a 'could not detect digest' message right above ^"
    END
```

https://ci.earthly.dev/logs?logId=acb8cf1f-b25d-44cf-89ca-aad3e08d8880

**Comment by mitre-tm** [comment]
For reference, the `LOCALLY` is not required:
```earthly
VERSION 0.6

up:
  FROM earthly/dind:alpine
  WITH DOCKER --pull=postgres:13.7
    RUN echo "There might be a 'could not detect digest' message right above ^"
  END
```
Running on my local machine:
```sh
$ earthly -v
earthly version v0.6.26 4a8d66e3b30d8ee758e7d71b40bc027f92e9adf4 linux/amd64; Ubuntu 22.04.1 LTS (Jammy Jellyfish)

$ earthly -P +up
 1. Init 🚀
————————————————————————————————————————————————————————————————————————————————

           buildkitd | Found buildkit daemon as docker container (earthly-buildkitd)

 2. Build 🔧
————————————————————————————————————————————————————————————————————————————————

 earthly/dind:alpine | --> Load metadata linux/amd64
       postgres:13.7 | --> Load metadata linux/amd64
       postgres:13.7 | --> DOCKER PULL postgres:13.7
       postgres:13.7 | [██████████] 100% resolve docker.io/library/postgres:13.7@sha256:03652c675ae177af98ddd50f9f4b4b2cf8ad38d0e116aa68fe670fbc2cf250fc
              output | --> exporting outputs
              output | [██████████] 100% exporting layers
              output | [██████████] 100% exporting manifest sha256:8df44890dd12b59862772032c65555cd2dc3b39fc73b724df0a2cda71a83227b
              output | [██████████] 100% exporting config sha256:b3591b962136e747c72a5d0e788551cb6b8163f8c577d97ce933cc86d22ab973
              output | [          ]   0% transferring docker.io/library/postgres:13.7
Warning: Could not detect digest for image postgres:13.7. Please update your buildkit installation.
                 +up | --> FROM earthly/dind:alpine
                 +up | [██████████] 100% resolve docker.io/earthly/dind:alpine@sha256:9b09804c68a2c68195b71e61a09616657b8f0a5ca01b4e029f710c7ca2396dc6
                 +up | *cached* --> WITH DOCKER (install deps)
                 +up | *cached* --> WITH DOCKER RUN --privileged echo "There might be a 'could not detect digest' message right above ^"
              output | [██████████] 100% transferring docker.io/library/postgres:13.7

 3. Push ⏫ (disabled)
————————————————————————————————————————————————————————————————————————————————

To enable pushing use earthly --push

 4. Local Output 🎁
————————————————————————————————————————————————————————————————————————————————



========================== 🌍 Earthly Build  ✅ SUCCESS ==========================

Shareable link: https://ci.earthly.dev/logs?logId=302e0d63-7bd5-4f7c-b47e-7c5a98ff5b84
```

PS: for some reason the `Warning: Could not detect digest for image postgres:13.7. Please update your buildkit installation.` does not show up in the shareable link

**Comment by mitre-tm** [comment]
Do we have any updates and/or suggestions on how to mitigate this?

**Comment by rrjjvv** [comment]
I started seeing this tonight (I'm fairly certain it's the first time).  I don't have any smoking guns to offer, but I do have a little I can contribute:
1. Though @mitre-tm didn't explicitly call it out above, this affects `--pull` as well as `--load` (for me at least); I'm not using `LOCALLY`
2. This isn't specific to postgres (which I'm not using at all).  My `--pull` and `--load` are of various OSes and parent images.

Since I first noticed this, I'm seeing it 100% of the time that I'm looking for it (i.e., I'm not actively trying to diagnose this so I can't say it is 100%, but it has been present every time I paid attention).  I don't know yet whether this holds true to multiple projects or not (I'm trying to get my current project done).  I've done simple/easy things like stopping/recreating the earthly container and restarting the docker daemon, which had no impact.

There are two "new" things that I'm trying to do tonight (which happens to be the first night I've experienced this issues):
1. It's my first time trying to utilize custom secrets providers
2. It's the first time I've tried running two `WITH DOCKER` blocks in the same target

There's no obvious reason to think either is (directly) connected.  And I'm fairly confident that the issue did not start in direct response to either of those.  But it was my first time trying both of those things, and the first time I've witnessed this issue, so...

If I get free time (or if it starts having a real impact) I can try experimenting more, but figured I'd pass on what I've seen as of now.
