### ISSUE TITLE
CACHE that can be shared between targets

### ISSUE THREAD

**Issue by brandonSc** [earthly/earthly#2592]
The contents of a directory created using the `CACHE` command only behave as a cache mount within a single target. When a target is finished building, the contents are converted to regular files on the system and saved to the image. This means that a subsequent target can access the files, but not treat them as a cache mount. 

In some cases, however, users would like to continue using the same cache in a subsequent target.

**Ideas:**
We could potentially support this by remounting the same cache volume to a new target. Perhaps naming the cache volume, so that the same name can be referenced in another target. Here's an example:

```earthly
target-a:
  FROM alpine
  CACHE --id=my-cache /dest
  # add files to cache

target-b:
  FROM +target-a:
  CACHE --id=my-cache /dest
  # continue adding files to same cache
```

In this scenario, files added in target-b would also be available in target-a. 

Another idea mentioned by a user was that CACHE declared in the base of an Earthfile could be retained as a cache in the subsequent targets.

**Comment by talios** [comment]
(as mentioned on slack) - For my usecase - we have a bunch of projects that are all separate repos - some maven/java projects, some leiningen/clojure (also jvm) projects, and non-monorepo, with different release cadences.

Primarily we want to cache the base/shared dependencies (and released versions of our own artifacts) for speed, rather than downloading from the ’net all the time.

Occasionally, we want to refer to unreleased SNAPSHOT versions which get installed into the local maven repository (some build tools refer to this the build cache - but it also includes the upstream artifacts) - so want disparate builds to write to that directory, and other another read that SNAPSHOT.

We could deploy to a SNAPSHOT repository - but that can lead to poisoned repositories if run under a CI system with concurrent builds running from different devs (less of an actual problem now, but it has been an issue in the past ).

**Comment by alexcb** [comment]
#1129 tracks the same idea.
