### ISSUE TITLE
`LABEL` error is unclear when quotes are misused

### ISSUE THREAD

**Issue by alexcb** [earthly/earthly#2656]
```
VERSION 0.7

test:
  FROM alpine
  RUN echo https://github.com/earthly/earthly > url
  LABEL "org.opencontainers.image.source=$(cat url)"
```

fails:

```
Error: build target: build main: failed to solve: resolve build context for target +test: Earthfile line 6:52 '
': invalid syntax
```

**Comment by alexcb** [comment]
https://github.com/earthly/earthly/blob/main/earthfile2llb/interpreter.go#L1423-L1444 makes calls to expand args, but it's not clear how `"org.opencontainers.image.source=$(cat url)"` ends up being split into `"org.opencontainers.image.source", "=", $(cat url)"`

**Comment by alexcb** [comment]
Note that this **does** work

```
VERSION 0.7

test:
  FROM alpine
  RUN echo https://github.com/earthly/earthly > url
  LABEL org.opencontainers.image.source="$(cat url)"   # note the quotes are located after the `=`.
```

**Comment by alexcb** [comment]
this too works:

```
VERSION 0.7

test:
  FROM alpine
  RUN echo https://github.com/earthly/earthly > url
  LABEL org.opencontainers.image.source=$(cat url)
```

**Comment by alexcb** [comment]
stretch goal: currently `LABEL` only appears under:

```
$ head tests/smoke.earth
VERSION 0.7
# This is a smoke test for parsing. We don't actually check that the config was
# set correctly.
FROM alpine:3.15
test:
    LABEL a=b c=d "e    eee = ee"=fff
    LABEL x=y
    LABEL abc.def.ghi=jkl
```

we should create an integration test that validates the label is correctly produced in the built image.

**Comment by nelsam** [comment]
For clarification's sake: `LABEL "org.opencontainers.image.source"="$(cat url)"` also works.

`LABEL "somelabel=somevalue"` should _not_ be valid syntax, correct? The issue mentions `"org.opencontainers.image.source=$(cat url)"`, but that is _one value_ - we _should not_ split on the equals sign there. Since the `=` is _inside_ of the quote pair, that equates to `LABEL labelKey`, and our parser grammar requires a label statement to be `LABEL (labelKey EQUALS labelValue)*` - so the `=` cannot be inside of the quote pair to be valid syntax. 

The error message is obtuse (and this is not the only case where an error message is obtuse), so I would like to improve the error message - but I want to make sure that the problem is specifically that the error message is not clear enough to track down why the `LABEL` failed.

**Comment by alexcb** [comment]
> LABEL "somelabel=somevalue" should not be valid syntax, correct?

That's a really good point.

where as `LABEL "$KEY"="$VALUE"` should be valid (as you point out, it already works).

It seems like the only issue is the error is not obvious.
