### ISSUE TITLE
Secrets should have precedence over args

### ISSUE THREAD

**Issue by vladaionescu** [earthly/earthly#2657]
In the following example

```Earthfile
ARG FOO
RUN --secret FOO echo $FOO
```

The value currently seems to be the one of the ARG. Since --secret is more specific (it applies to that single RUN command only), it should probably have precedence over the ARG.

**Comment by genestack-okunitsyn** [comment]
I'm sorry, I have a small proposal:

In my mind that is not so simple, because ARG KEY=VALUE shows in logs, so it’s a bit confusing if we see in logs one value, but earthly uses another one in build stage.

My proposal - catch "mistakes" like this and show a "WARNING" or "ERROR" and stop a build.

**Comment by alexcb** [comment]
Perhaps we need the ability to unset an arg, e.g. `ARG --unset FOO`

Then we could support returning an error, since users could then unset ARG which come from a previous target, then continue with a `RUN --secret FOO`

Here's a similar unexpected precedence issue:

```
VERSION 0.7

test-base:
  FROM alpine
  ARG FOO=frombase

test:
  FROM +test-base
  ARG FOO=fromarg
  ENV FOO=fromenv
  RUN env | grep FOO
```

in this case we get `+test | FOO=fromarg`, where the first declared `ENV` or `ARG` of the directly referenced target takes precedence.

#1575 relates to a new ARG setup, which might have some overlap here.

**Comment by alexcb** [comment]
rather than display a WARNING, we will have a verboseprintf that will display all the secret environment names instead.
