### ISSUE TITLE
0.7.0 Regression? Unindented comments in recipe bodies cause parser errors

### ISSUE THREAD

**Issue by jhberges** [earthly/earthly#2697]
The following fails to execute after upgrade from 0.6.30 to 0.7.0:

```
1: my-target:
2:     RUN some_command
3:     # Comment regarding something
4:     SAVE ARTIFACT /stuff
```
`earthly` will fail with an error like:

```
Error: build target: build main: failed to solve: <...> Earthfile line 4:0 '    ': invalid syntax

Hints:
  - I got lost looking for '<EOF>'
```

That is, it will fail on the first line after an inline comment in a target.

This might very well be "as expected", but I couldn't find a mention regarding it in the docs.
Besides, it *did* work in 0.6.30 ;-) 

Regards, Jan-Helge

**Comment by nelsam** [comment]
@jhberges can you give me a more complete failing example? The following appears to work:

```Earthfile
VERSION 0.7
FROM alpine

my-target:
     RUN echo foo > stuff
     # Comment regarding something
     SAVE ARTIFACT /stuff
```

**Comment by jhberges** [comment]
Sure, @nelsam :

[Earthfile.zip](https://github.com/earthly/earthly/files/10803811/Earthfile.zip)

Actually, after testing it I think it might be the indentation changes. 
Uncommenting the line with a hash in column 1 gives the appropriate error (i.e "image with no name").
The uncommented "GIT CLONE" below:

```shell 
$ cat Earthfile 
VERSION 0.7
FROM golang:1.20.1-alpine3.17
WORKDIR /defs

my-target:
    ARG TARGETARCH
    FROM balenalib/${TARGETARCH}-ubuntu-node
    COPY *.tmpl /defs
    SAVE IMAGE --cache-hint

unrelated-target:
    FROM alpine
    RUN echo foo > stuff
    # Comment regarding something
#    GIT CLONE  https://github.com/seamia/protodot.git /defs/protodot
    # Another sub-comment
    WORKDIR /defs/protodot
    RUN go build
    
$ earthly --version
earthly version v0.7.0 cb2217400afdce4b49221dfa2eb64c06373141ce linux/amd64; Ubuntu 22.10 (Kinetic Kudu)

$ earthly --no-cache +my-target 
 Init 🚀
————————————————————————————————————————————————————————————————————————————————

           buildkitd | Found buildkit daemon as docker container (earthly-buildkitd)

 Build 🔧
————————————————————————————————————————————————————————————————————————————————

Share your logs with an Earthly account (experimental)! Register for one at https://ci.earthly.dev.
Error: build target: build main: failed to solve: resolve build context for target +my-target: Earthfile line 13:0 '    ': invalid syntax

Hints:
  - I got lost looking for '<EOF>'

```

**Comment by nelsam** [comment]
Ah, I think I get what's happening. Since we are now parsing comments instead of ignoring them (and perhaps more importantly: since they _need_ to be parsed immediately before the next target token in order to be detected as documentation), they can trigger `DEDENT` tokens. I think that the unindented `GIT CLONE` line takes the parser out of "recipe" mode, and it's now expecting a new recipe (target or user-defined command) to start on the line after. That's why `    ` is part of the error message - it expects the next non-comment line to be unindented.

We can definitely make the error cleaner, but making the unindented comment parse as intended will take a bit more effort. Parsing significant whitespace is complicated.

@alexcb @vladaionescu This seems like an edge case, but I wouldn't be surprised if it's pretty common (e.g. developers commenting out a line to debug something may just comment column 0). I can see an argument for just improving the error message, but I suppose it's probably better to try to get our parser to handle this case, right?

**Comment by vladaionescu** [comment]
Yeah, makes sense - it would be nice to ignore that commented line altogether and not emit a DEDENT in that case.
