### ISSUE TITLE
Support for OrbStack

### ISSUE THREAD

**Issue by vladaionescu** [earthly/earthly#2704]
OrbStack is a Docker App alternative: https://orbstack.dev/.

Earthly doesn't currently work with it. Some people in the community have asked for it.

**Comment by vladaionescu** [comment]
Error encountered: https://app.warp.dev/block/dj92bKRXXiW8K4XhWz8oWv

**Comment by mattste** [comment]
This has been fixed on OrbStack's side with OrbStack v0.1.8. 

Info from OrbStack developer:
>OrbStack's subnet isn't configurable, but I rebuilt it with 172.31 and it fixed the issue. Originally, I picked 172.30 for internal use because Docker starts at 172.17 and the last subnet in that private range (31) seemed like a potentially common choice — I guess you made a similar decision. Is there another IP range that you think would help minimize conflicts? I only need a /24 for internal use

**Comment by kdrag0n** [comment]
Yep, this issue was caused by a conflict between the subnets used by Earthly's buildkitd and internally by OrbStack, which both fell under 172.30.0.0/16. Changing it to 172.31 was just a quick test to confirm the issue; OrbStack v0.1.8 has switched to an entirely different IP range that is very unlikely to conflict with anything. It's also mentioned in the [release notes.](https://docs.orbstack.dev/release-notes)

**Comment by vladaionescu** [comment]
Many thanks for making this work from the OrbStack side @kdrag0n! Closing as resolved.
