### ISSUE TITLE
[FeatureRquest/Question] Enable `IF` as the first command

### ISSUE THREAD

**Issue by zaufi** [earthly/earthly#2776]
My `Earthfile` has a target `all` which I wanted to make optionally "depends" on some others:
```
deb-build:
    # …

devel:
    # …

all:
    # Primary images
    BUILD +deb-build

    # NOTE Uncomment to make it work
    # LOCALLY

    ARG WITH_DEVEL
    IF [ ${WITH_DEVEL} -gt 0 ]
        BUILD +devel
    END
```

However, using `IF` enforcing me to put `LOCALLY` before:
```
Error: build target: build main: failed to solve: Earthfile line 104:4 apply IF: 
the first command has to be FROM, FROM DOCKERFILE, LOCALLY, ARG, BUILD or IMPORT
```

Strictly speaking, the first command of the target `all` is `BUILD`. This makes the reported error a bit controversial.

Q: Is using `LOCALLY` OK for this purpose?

**Comment by alexcb** [comment]
It's not obvious, but `IF` will execute `[ ${WITH_DEVEL} -gt 0 ]` (i.e. by running `/usr/bin/[`, or by having the shell short-circuit it).

For this to work, the target must have a `FROM ...` (e.g. `FROM alpine`). You could use `LOCALLY`, but it's better to use a container (since `LOCALLY` doesn't work when earthly is run under the stricter `--ci` mode).

**Comment by zaufi** [comment]
Thanks for the answer. But how I can use `BUILD` in a container? I wanted to make the building of some targets conditionally (i.e., smth like a build option for "normal" build systems wich brings some features).

**Comment by alexcb** [comment]
have you tried using `FROM alpine`?

```
all:
    FROM alpine
    ARG WITH_DEVEL
    IF [ ${WITH_DEVEL} -gt 0 ]
        BUILD +devel
    END
```
