### ISSUE TITLE
Running earthly as docker image?

### ISSUE THREAD

**Issue by bukowa** [earthly/earthly#306]
I cannot find any refference to that, i imagine running earthly in docker image with priviliged =true

**Comment by vladaionescu** [comment]
Hi @bukowa - sorry for the late reply. We have a docker image, but we have not documented it: https://hub.docker.com/repository/docker/earthly/earth. The tag `latest` points to the latest released version of `earth`. The entrypoint is set to `earth` itself.

It should work as you would expect for the most part - but treat it as experimental since it's not officially supported. We plan to support it in the future. Keep in mind that you need to also mount `/var/run/docker.sock` to be able to output docker images.

Curious: What's the use-case for running earth as a docker image? Are you using earth in a CI? Very curious about your use-case / specific setup!

**Comment by bukowa** [comment]
Thanks for input. I was having similiar problems to what you described in your blog post
![1 NsfCLKr0C5CNlF2ZeMhzzA](https://user-images.githubusercontent.com/38087302/94309624-a786a900-ff78-11ea-998c-2c1fcde0c3c0.png)

I imagine to except the same while not being able to run CI/CD tool in docker directly. While i was looking for solution i thought the same way - describing my whole pipeline in a Dockerfile - because for me - Dockerfile just always works - i have a project where i run all tests in the same Dockerfile used to build  the final image - if they won't pass the image won't be build:

````Dockerfile
FROM php@sha256:cc9d43710ae41eaf879c7f7b6458f5a0988093602bb827cbf14fc2458d753ace as base
.... < some stuff not important > ...

FROM golang@sha256:5219b39d2d6bf723fb0221633a0ff831b0f89a94beb5a8003c7ff18003f48ead as script
ENV WORKDIR="/app/build/src"

ENV CGO_ENABLED=0
ENV GO111MODULE=on

WORKDIR $WORKDIR
COPY . .
RUN go build -mod vendor \
    -o /app/build/gophpcs \
    gophpcs/main.go
RUN go build -mod vendor \
    -o /app/build/runtests \
    tests/main.go

# final image
FROM base as final
COPY --from=script /app/build/gophpcs /usr/local/bin/gophpcs
COPY --from=script /app/build/runtests /usr/local/bin/runtests
RUN chmod +x /usr/local/bin/gophpcs /usr/local/bin/gophpcs

# test image run in build
FROM final as test
WORKDIR "/app/test"
COPY tests .
RUN runtests .

# once again set final as the image
FROM final
ENTRYPOINT ["gophpcs"]
````
But here are limitations - because - how could we spawn additional services (docker images) in Dockerfile itself? That's when i found `earthly` - but i never had a chance to use it - because i could not find any docs that allow one - click (docker command) use case.

**Comment by vladaionescu** [comment]
Got it - Earthly is primarily meant to be run directly, not as a Docker image. I recommend running earth directly, not as an image.

Behind the scenes, it spawns a docker container that runs a [Buildkit](https://github.com/moby/buildkit) daemon, which is used to execute the builds. Buildkit then uses containers to perform all build operations. So although earth itself is not meant to be run in docker, all of the builds executed via earth are actually executed in containers. That should prevent any problems due to inconsistencies between environments.
