### ISSUE TITLE
Referenced secrets does not invalidate cache

### ISSUE THREAD

**Issue by dustyhorizon** [earthly/earthly#3386]
**What went wrong?**
Secrets does not invalidate the target when the value have changed.

Example Earthfile:
```
VERSION --global-cache --arg-scope-and-set 0.7

build:
   RUN --secret SOME_BUILD_KEY echo "secret is ${SOME_BUILD_KEY}"
```

To reproduce:
- Run `earthly --secret SOME_BUILD_KEY="aaa" +build`
- Notice that `secret is aaa` is printed in the logs somewhere
- Run `earthly --secret SOME_BUILD_KEY="bbb" +build`
- No output this time as the layer is cached i.e. `*cached* --> RUN echo "secret is ${SOME_BUILD_KEY}"`

**What should have happened?**
The hash value of secret(s) should be taken into account when determining to invalidate the cache or not.

**Other Helpful Information**
```
❯ earthly --version
earthly version v0.7.20 9600f376026c11d23eb43fc68ad716d6ae4cca2e linux/amd64; Manjaro Linux  homebrew
```

**Comment by alexcb** [comment]
This is working as intended; see #2030 for a proposal to allow for changing this.

**Comment by tmladek** [comment]
Sorry to revive this issue, but it seems more appropriate to ask here rather than in #2030 (and I did try asking on the Earthly Slack).

What workarounds would you suggest when a cached secret is breaking the build? For example, I have my signing key passed as a secret, and the key has expired. Or simply when an incorrect secret is passed initially, by accident.

Is purging the **entire** cache the only way? Could it be possible to purge cache only for a given step, or a target?

Thanks!
