### ISSUE TITLE
Auto-skip purge

### ISSUE THREAD

**Issue by mikejholly** [earthly/earthly#3539]
**Use case**

As a user of auto-skip, I'd like to be able to purge AS hashes from the remote database in order to bypass subsequent AS checks without code changes. I'd like to delete hashes by org name, project name, & individual hash.

**Expected Behavior**

CLI invocations may look something like:

```
earthly auto-skip prune --org <org-name>
```

```
earthly auto-skip prune --org <org-name> --project <project-name>
```

```
earthly auto-skip prune --digest <digest>
```

The exact command (or subcommand) is up for discussion.

**Comment by alexcb** [comment]
Just in case it's not known (and for more transparency to our users), the askv server already supports these calls:

```
  rpc PrunePipeline(PrunePipelineRequest) returns (PrunePipelineResponse) {}
  rpc PruneProject(PruneProjectRequest) returns (PruneProjectResponse) {}
  rpc PruneOrg(PruneOrgRequest) returns (PruneOrgResponse) {}
```

see https://github.com/earthly/cloud-api/blob/main/askv/askv.proto for details.

Unfortunately there's no digest-specific prune function that already exists.

Furthermore, the Pipeline-based one is no longer applicable since the CI offering has been shutdown.
