### ISSUE TITLE
Earthly cloud questions

### ISSUE THREAD

**Issue by wataruian** [earthly/earthly#3887]
Hi, I am trying earthly cloud and am having a great time!

I recently activated my account (organization) and got the free 6000mins of build time which is great.

From the earthly cloud website, I can switch to my personal account and organization via the organization dropdown.

In the dashboard, I can see my running satellites but I can't seem to see my build history, the list says `No builds yet...`
<img width="1297" alt="Screenshot 2024-03-12 at 8 51 28 PM" src="https://github.com/earthly/earthly/assets/32057659/85ab2e83-277b-4694-b0a4-40f978513688">

I am not sure why I still don't have the build history but every time I complete a build I can access the generated link and I also selected my organization as the default from the CLI:
<img width="681" alt="Screenshot 2024-03-12 at 8 56 31 PM" src="https://github.com/earthly/earthly/assets/32057659/6c84e973-3ee2-41a6-9eea-4efccccaec59">

Also, I can't seem to navigate to the projects list and or secrets list, etc (does it exist?).

All I have is the "Dashboard" which shows the satellite status (I can't do anything with it, and can't manage from the UI). 

Is it because I only have a free account?

**Comment by alexcb** [comment]
There was a bug fixed in #3836; can you make sure you are using the latest v0.8.5 release of earthly and also try defining a `PROJECT <org>/<project_name>` command in your Earthfile (right after the `VERSION` command).

You may need to create a project via `earthly project create`.

Regarding secrets, you will need to use the cli to manage them (see `earthly secrets --help`); we hope to eventually have a web-based interface for managing them, but it doesn't exist currently.

**Comment by alexcb** [comment]
Another option to using the `PROJECT` command is to run `earthly org select ...`.
