### ISSUE TITLE
Proposal: First-party support for AWS credentials

### ISSUE THREAD

**Issue by vladaionescu** [earthly/earthly#578]
Automatically pick up credentials from the typical location on the host system and pass them on inside the build environment.

Details TBD

**Comment by vladaionescu** [comment]
This is no longer needed as there is a pretty good way to use AWS credentials via the AWS credential helper for Docker: https://docs.earthly.dev/guides/pushing-and-pulling-images-with-cloud-providers

**Comment by MatthiasScholzTW** [comment]
It seems the link is broken. The closed I could get was finding this part of the documentation:

- https://docs.earthly.dev/docs/guides/configuring-registries/aws-ecr

Nevertheless I feel this is only part of the solution. Since AWS credentials might be needed for other actions than pulling and pushing images from or to an AWS ECR repository. E.g. running some infrastructure provisioning to create the ECR repository, maybe using a tool like terraform. In this case the credentials would still be needed as environment variable or additional file.

**Comment by dchw** [comment]
@MatthiasScholzTW What I have been doing (that seems to work fine) is mount the secrets as files into the usual places for the tooling to use. See [this section of this blog post](https://earthly.dev/blog/build-your-own-ngrok-clone/#create-using-earthly), where I am using the `awscli` tool to build all sorts of resources.

I agree it could be a little better if the `--secret-file` let you specify a directory; but its certainly better than having to provide and manage assumed roles or all the environment variables individually.

This approach could work well with Terraform, and even let you use different `AWS_PROFILES` for different parts of your build.

Does this get closer to what you are thinking?

**Comment by MatthiasScholzTW** [comment]
Thanks for the providing this detailed examples. It illustrates well how a possible solution could look like.

Unfortunately it is not applicable for my use case since I am using [aws-vault](https://github.com/99designs/aws-vault) (a handy tool increase security by avoiding storing AWS credentials in plain text) to create temporary credentials. It works like this: `aws-vault exec <profile> -- earthly +do-something` - the tool will add the AWS credentials to the process context.

The whole point is regarding supporting dynamically created credentials. The use case expands beyond `aws-vault`, e.g. when SSO providers are used to secure AWS access.

A possible solution could be using for example `--build-arg AWS_REGION` without specifying a value and taking the one provided by the environment.
