### ISSUE TITLE
SSH agent socket passing

### ISSUE THREAD

**Issue by a-hat** [earthly/earthly#58]
Hi, I am trying to download a go module from a private github repository within an earthly build and I cannot figure out how this is supposed to work. In the earthly documentation I read about [SSH agent socket passing](https://docs.earthly.dev/guides/auth), but I think this is only intended for the GIT CLONE command and won't work for `go mod download`?

So I tried to do it like described in the [buildkit doc](https://docs.docker.com/develop/develop-images/build_enhancements/), but then docker complains about the missing mount point:

```
RUN git config --global url."ssh://git@github.com/some-org/".insteadOf https://github.com/some-org/ 
RUN mkdir -p -m 0600 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
RUN --mount=type=ssh GOPRIVATE=github.com/some-org go mod download
```
Could you please point me in the right direction?

**Comment by vladaionescu** [comment]
Hi @a-hat, the mount type ssh is not yet supported in Earthly.

One workaround might be to pass in the SSH private key as an [Earthly secret](https://docs.earthly.dev/earthfile#secret-less-than-env-var-greater-than-less-than-secret-ref-greater-than), then placing it in the right place in `.ssh` in the container, performing `go mod download` and then removing the private key. This should be a single RUN command (so the private key doesn't remain persisted in the image layers).

It's less elegant than it should be - so we'll likely support passing private ssh info properly at some point.

**Comment by vladaionescu** [comment]
Just occurred to me, that another workaround would be to use username-password (instead of SSH) for the git clone of the private repos. Instead of the password, you can use a GitHub generated token and pass that on as an Earthly secret (GitHub [allows use of tokens instead of passwords](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line#using-a-token-on-the-command-line)). You would however need to use a custom git credentials helper - I've used something like this [in here as an example](https://github.com/earthly/earthly/blob/master/buildkitd/build.earth#L14).

**Comment by vladaionescu** [comment]
@zenyui also reported this inconvenience just now.

**Comment by alexcb** [comment]
We just released a new version with support for SSH agent socket passing in https://github.com/earthly/earthly/releases/tag/v0.3.6

This should hopefully do the trick:
```
RUN git config --global url."ssh://git@github.com/some-org/".insteadOf https://github.com/some-org/ 
RUN mkdir -p -m 0600 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
RUN --ssh GOPRIVATE=github.com/some-org go mod download
```

**Comment by zenyui** [comment]
That's huge, thanks team. What's the typical latency for availability via homebrew?

**Comment by alexcb** [comment]
it's usually a few hours, but we ran into a request to change how we reference the version in https://github.com/Homebrew/homebrew-core/pull/61187

so hopefully we'll get the patch updated by tomorrow.
