### ISSUE TITLE
Proposal: User-defined commands (UDCs)

### ISSUE THREAD

**Issue by vladaionescu** [earthly/earthly#581]
### Proposal

This proposal includes three key parts:
  * The transition from the syntax `--build-arg XYZ=value` to `--xyz=value`
  * ~The extension of ARGs to allow other types besides the default string type~ EDIT: This part has been abandoned for now.
  * User-defined commands (UDCs). A concept somewhat similar to Earthly targets - they can be referenced across directories and projects and they are made up of a series of Earthly commands. However the key difference is that Earthly targets come with a specific build context (the dir where `COPY ./file ./dest` copies files from) and also Earthly targets reset the build environment as a result of a `FROM` command. User-defined commands on the other hand inherit both the build context and the build environment from the caller.

### Example

```Dockerfile
INSTALL_DEPS:
  COPY go.mod go.sum ./
  RUN go mod download
  SAVE ARTIFACT go.mod AS LOCAL go.mod
  SAVE ARTIFACT go.sum AS LOCAL go.sum
```

Usage example

```Dockerfile
IMPORT github.com/bla/bla+INSTALL_DEPS

code:
  +INSTALL_DEPS
  COPY src ./src
  RUN go build …
```

OR (without the IMPORT)

```
code:
  github.com/bla/bla+INSTALL_DEPS
  COPY src ./src
  RUN go build …
```

An example with args

```Dockerfile
COMPILE_GO:
  ARG copy=./
  ARG out
  ARG GOCACHE=/go-cache
  COPY $copy ./src
  RUN --mount=type=cache,target=$GOCACHE \
    go build -o $out src/*.go

command1:
  +COMPILE_GO --copy=./cmd/command1 --out=./build/command1

command2:
  +COMPILE_GO --copy=./cmd/command2 --out=./build/command2
```

### Notes

* User-defined commands (UDCs) are distinguished from targets by the fact that they are all upper case. Targets may not have upper case characters.
* A UDC executes in the context in which it is called. FROM is not allowed.
* The build context is whatever build context the caller has (COPY commands work as if they are inlined in the caller)
* Arguments are defined the same way as build args, but are lower-case and can be specified like command-line args eg `ARG copy` can be passed as `+<command> --copy=....`
* In UDCs args are not transitive - they have to be passed explicitly

### ARG types

```Dockerfile
MY_COPY:
  ARG --bool recursive
  ARG --positional --string src
  ARG --positional --string dest=./
  RUN cp $(if $recursive ==  "true"; then printf -- -r; fi) "$src" "$dest"

some-target:
  +MY_COPY --recursive ./from ./to
```

* Possible types: `string`, `bool`, `artifact`, `image`
* If no type specified, `--string` is implied (backwards compatibility)
* Artifact is passed in as an Earthly artifact ref, but within the command definition it comes as a string of a mounted path containing the artifact.
* Image is passed in as an Earthly target ref, but within the command definition it comes as a docker label (similar to `WITH DOCKER --load`).

### TODO

* An inherent limitation of the Earthfile syntax is that it doesn't provide conditionals or loops and using the bash `if` and `for` would not be enough when used in combination with UDCs (UDCs cannot be called from within bash expressions). This may or may not be a problem for some use-cases. There may be a need for new commands like `FOR`/`WHILE` and `IF`.

### Possible future extensions

* UDCs containing `FROM`. If a UDC contains a `FROM <target>`, it would not execute in the context of the caller, but rather in its own isolated context. In this form, it works more like a black box with inputs and outputs.
* Using UDCs together with `WITH`. For example, if `WITH DOCKER` could be implemented as such a `+DOCKER` UDC. This means functions would have access to more implications / functionality (this could also be a risk of creating too much complexity in the syntax). The way it might work could be that the following two would be equivalent (do is interpreted as the body of a `WITH`):
  
  ```Dockerfile
  THE_DO_BODY:
    RUN ...
    COPY ...

  +COMMAND --some-arg=val --do=+THE_DO_BODY positional1 positional2
  ```
  
  ```Dockerfile
  WITH +COMMAND --some-arg=val positional1 positional2
    RUN ...
    COPY ...
  END
  ```

### Use-cases

* Build templates - define a standard way to build a certain type of project. The template is defined in a central location (eg a common github repository) and each project needing to build in that way can simply reuse that definition.
* Community-provided scripts / libraries that can be imported from GitHub. Compared to importing a target, the UDC does not come with the build context too - it only brings the instructions, which execute on the callers context.
* Standard libraries (possibly first-party) that can be used for common tasks.

**Comment by sascha-wolf** [comment]
As a user I'd like to give my (maybe naive) perspective on this proposal. 🙂

First of all I'd really like the option to execute a series of pre-defined earthly commands, as that would enable me to define a common set of targets which could be reused across multiple projects. Similar to how CircleCI orbs allow me to reuse build steps.

There is one observation I'd like to share though:

## Implicitness and Discoverability

To summarize the proposal, a reusable target would be defined like this:

```
INSTALL_DEPS:
  COPY go.mod go.sum ./
  RUN go mod download
  SAVE ARTIFACT go.mod AS LOCAL go.mod
  SAVE ARTIFACT go.sum AS LOCAL go.sum
```

And used like this:

```
IMPORT github.com/bla/bla+INSTALL_DEPS

code:
  +INSTALL_DEPS
  # ...
```

Or this:

```
code:
  github.com/bla/bla+INSTALL_DEPS
  # ...
```

Apart from the usage of `IMPORT` everything depends on __implicit__ conventions. While that's not necessarily a bad thing in of itself, it lends itself bad to discoverability (or "googling" for that matter). What do I mean by that?

Let's assume a colleague joins a team where earthly is used. They have no prior experience with earthly, the only context they have is another colleague saying "it's like Makefiles and Dockerfiles had a baby". What would they think, if they'd see code as the one above? While the `IMPORT` could be a hint, the "non-`IMPORT`" version would probably lead to a raised eyebrow at least. And - mabye more importantly - what would said colleague google?

Maybe this:

> earthfile github link with target

Or maybe this, if they already skimmed the docs:

> earthfile remote target without command

I hope it's now clear what I mean, when I mention discoverability.

While the proposed syntax offers brevity, it does so for the cost of discoverability. It's optimized towards writing Earthfiles, not towards reading them.

### Alternative: Usage of Keywords

Instead of relying on implicit conventions, explicit keywords would resolve the issues mentioned above at the cost of increasing the amount of typing required. As Earthfiles are most likely more often read than written I consider this an acceptable trade-off.

I'd like to propose a slightly different syntax:

#### Exporting a target

```
EXPORT +install_deps, +build

install_deps:
  # ...

build:
  # ...

a_private_target:
  # ...
```

This would make `+install_deps` and `+build` available for `IMPORT`ing which also has a nice symmetry to it. For convenience the `EXPORT` keyword could also offer a `EXPORT +*` shortcut which exports all targets.

#### Reusing a Remote Target

The same principle 

```
IMPORT github.com/bla/bla+install_deps

code:
  INLINE +install_deps
  # ...
```

Or without `IMPORT`:

```
code:
  INLINE +github.com/bla/bla+install_deps
  # ...
```

The same principles apply here. By using an explicit keyword (`INLINE`) the functionality becomes discoverable for potential users, as they now can google:

> earthfile inline

---

Of course the above mentioned keywords are just examples and open for debate. But I strongly believe that a "keyword-based" approach would bring more advantages than costs with them.

I'd be happy to hear your thoughts on this. 🙂

**Comment by vladaionescu** [comment]
You raise some very relevant points @sascha-wolf.

I like the general direction although don't necessarily agree 100% with everything. Some remarks:
* When defining a target to be exported it is not immediately obvious to the reader whether it's a UDC or a regular target. I realize that the lower-case vs upper-case convention requires prior knowledge, but it's better than nothing.
* I like the idea of `EXPORT` - it makes it obvious which targets are more like API and need to be maintained as such for external consumption. I'm not a fan of maintaining a list separate from the definition though. Wonder if this "export" could instead be declared within the target itself. Maybe this also solves the point above (eg `UDC` and `UDC --export`). Have to think about this a bit more.
* Don't agree 100% with `github.com/foo/bar+COMMAND` being completely unreadable - people would figure what `github.com/...` prefix is about I imagine. We try not to introduce any magical characters or concepts in Earthly - though we made an exception with `+` and plan to have it be the only magical construct of the syntax.
* I like the idea of `INLINE` - might help with readability. Wonder if there are other alternative words that we could use for this.

**Comment by agbell** [comment]
I like the Dhall idea @sascha-wolf!  

how would `INLINE` work with arguments?  

`INLINE` implies to me that declaring an arg before `INLINE` or in the first line of whatever was inlined would be equivalent and that you would pass in arguments by declaring a number of args before calling.  

```
+MY_COPY ./from ./to
```
would become

```
ARG from=./from
ARG to=./to
INLINE MY_COPY
```
I like the first syntax because it makes UDCs feel like built-in commands  (`RUN`, `ARG`, etc).  They execute in the context where they are called from and take arguments directly.

**Comment by vladaionescu** [comment]
I was thinking that `INLINE` would not necessarily change anything regarding parameters are passed. It can still be `INLINE +MY_COPY ./from ./to`.

**Comment by agbell** [comment]
We are now thinking about changing this based on feedback from @sascha-wolf and further discussions with @vladaionescu, @alexcb and @dchw.

Summary:
 * `IMPORT` remains the same
 * User defined commands must be in capitals and contain `USER COMMAND` as the first line
 * User Commands are called with the word `DO`
 
That would mean the example would become:
```
MY_COPY:
   USER COMMAND
  ARG --bool recursive
  ARG --positional --string src
  ARG --positional --string dest=./
  RUN cp $(if $recursive ==  "true"; then printf -- -r; fi) "$src" "$dest"
```
Usage
```
IMPORT github.com/bla/bla+INSTALL_DEPS

code:
  DO MY_COPY ./from ./to
 ..
```

`DO` and `USER COMMAND` and `IMPORT` keywords should aid discoverability (without the implications of shared scope that `INLINE` suggests).

**Comment by jwarlander** [comment]
Looks really promising!

I had a use case just now, where I wanted to perform my own "docker login" / "docker logout" commands before and after pushing an image to AWS ECR. The problem with implementing those as LOCALLY targets seems to be that I can't really put them properly into the dependency chain, so they're not really usable together with the Earthly push capabilities.

Would this proposal help? Eg. could I define DOCKER_LOGIN / DOCKER_LOGOUT as UDCs, both running with LOCALLY, and use them inside a target where I do a `SAVE IMAGE --push`, having them properly sequenced before & after the push?

**Comment by vladaionescu** [comment]
Not sure that it would - it's possible that things could run in the wrong order. We recommend using the AWS ECR credential helper for this: https://docs.earthly.dev/guides/auth#credential-helpers. Does that solve your issue?

**Comment by vladaionescu** [comment]
An interesting suggestion about pass-through args: https://github.com/earthly/earthly/issues/820#issuecomment-787141457

**Comment by vladaionescu** [comment]
The implementation for this is complete. We decided to punt on ARGs with types and on positional ARGs, to keep it simple.

Everything else is ready, however, and will be out in the next release. Until then I will also write up some documentation for this.

**Comment by parnham** [comment]
I've been testing this feature out and I like the concept but was wondering if the declaration could be made a little less verbose?
Since you would usually define a bunch of arguments for a command, such as
```
BUILD:
    COMMAND
    ARG distribution
    ARG tag
    ARG module
    RUN ...
```

Could that not be declared in a shorthand way
```
BUILD:
    COMMAND distribution tag module
    RUN ...
```

And potentially even allow for default values
```
BUILD:
    COMMAND distribution=bionic tag module
    RUN ...
```

**Comment by mologie** [comment]
The current forced scope of ARGs makes it very inconvenient to propagate information. For example, I am passing a `CI_PIPELINE_ID` into a `+BUILD` command, but this is rather awkward right now:

```
# earthly --build-arg CI_PIPELINE_ID=42 +baz
# working example with Earthly 0.5.22, but very verbose and ugly :(

BUILD:
    COMMAND
    ARG foo
    ARG ci_pipeline_id
    RUN CI_PIPELINE_ID=$ci_pipeline_id echo $foo bar $CI_PIPELINE_ID

baz:
    ARG CI_PIPELINE_ID
    DO +BUILD --foo=foo --ci_pipeline_id=$CI_PIPELINE_ID
```

It would be a lot nicer if I could just place the `ARG CI_PIPELINE_ID` right into the relevant command.

This is would look even better with the syntax suggested by @parnham: ARGs would work like expected, i.e. work with build-args, and thus be free of surprises. Command args otoh MUST be given with the COMMAND line:

```
# earthly --build-arg CI_PIPELINE_ID=42 +baz
# combining normal arg scope and parnham's syntax suggestion:

BUILD:
    COMMAND foo
    ARG CI_PIPELINE_ID
    RUN echo $foo bar $CI_PIPELINE_ID

baz:
    DO +BUILD --foo=foo
```
