### ISSUE TITLE
Document how to configure caching to use in CI/CD

### ISSUE THREAD

**Issue by edmondo1984** [earthly/earthly#678]
Many modern CI/CD platform execute different steps of the pipeline in a container and provide support for a persistent folder that one can use to pass data from one container to another one. Using Earth.ly to run multiple steps inside a build, or across builds, need to configure where the cache resides (an S3 bucket?) and I could not find any documentation about it

**Comment by vladaionescu** [comment]
Hi @edmondo1984 - there is native caching support within Earthly, documented here: https://docs.earthly.dev/guides/shared-cache. This uses a Docker registry as the cache storage. This is a relatively new feature and in experimental stage, that's why it's not yet propagated throughout the rest of the docs just yet.

The caching features that CI systems provide themselves are not performant enough from what we can tell from our testing. Main reason is that they store everything as a blob and is not very smart about peeking into that blob to upload/download only deltas.

Curious what your experience is with Earthly's shared caching feature - if you get a chance to leave some feedback either in our Slack or as a comment in https://github.com/earthly/earthly/issues/11.
